---
- name: config | Configuring Cassandra
  template:
    src: etc/cassandra/cassandra.yaml.j2
    dest: "{{ cassandra['root_dir'] }}/cassandra.yaml"
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart cassandra
